EVENT_IDS = {
    1: 'Pass',
    2: 'Offside Pass',
    3: 'Take On',
    4: 'Foul',
    5: 'Out',
    6: 'Corner Awarded',
    7: 'Tackle',
    8: 'Interception',
    9: 'Turnover',
    10: 'Save',
    11: 'Claim',
    12: 'Clearance',
    13: 'Miss',
    14: 'Post',
    15: 'Attempt Saved',
    16: 'Goal',
    17: 'Card',
    18: 'Player Off',
    19: 'Player on',
    20: 'Player retired',
    21: 'Player returns',
    22: 'Player becomes goalkeeper',
    23: 'Goalkeeper becomes player',
    24: 'Condition change',
    25: 'Official change',
    27: 'Start delay',
    28: 'End delay',
    30: 'End',
    32: 'Start',
    34: 'Team set up',
    35: 'Player changed position',
    36: 'Player changed Jersey number',
    37: 'Collection End',
    38: 'Temp_Goal',
    39: 'Temp_Attempt',
    40: 'Formation change',
    41: 'Punch',
    42: 'Good skill',
    43: 'Deleted event',
    44: 'Aerial',
    45: 'Challenge',
    47: 'Rescinded card',
    49: 'Ball recovery',
    50: 'Dispossessed',
    51: 'Error',
    52: 'Keeper pick-up',
    53: 'Cross not claimed',
    54: 'Smother',
    55: 'Offside provoked',
    56: 'Shield ball opp',
    57: 'Foul throw-in',
    58: 'Penalty faced',
    59: 'Keeper Sweeper',
    60: 'Chance missed',
    61: 'Ball touch',
    63: 'Temp_Save',
    64: 'Resume',
    65: 'Contentious referee decision',
    66: 'Possession Data',
    67: '50/50',
    68: 'Referee Drop Ball',
    69: 'Failed to Block',
    70: 'Injury Time Announcement',
    71: 'Coach Setup',
    72: 'Caught Offside',
    73: 'Other Ball Contact',
    74: 'Blocked Pass',
    75: 'Delayed Start',
    76: 'Early end',
    77: 'Player Off Pitch',
}

QUALIFIER_IDS = {
    1: 'Long ball',
    2: 'Cross',
    3: 'Head pass',
    4: 'Through ball',
    5: 'Free kick taken',
    6: 'Corner taken',
    7: 'Players caught offside',
    8: 'Goal disallowed',
    56: 'Zone',
    106: 'Attacking Pass',
    107: 'Throw-in',
    140: 'Pass End X',
    141: 'Pass End Y',
    152: 'Direct',
    155: 'Chipped',
    156: 'Lay-off',
    157: 'Launch',
    168: 'Flick-on',
    193: 'Goal Measure',
    195: 'Pull Back',
    196: 'Switch of play',
    210: 'Assist',
    212: 'Length',
    213: 'Angle',
    218: '2nd assist',
    219: 'Players on both posts',
    220: 'Player on near post',
    221: 'Player on far post',
    222: 'No players on posts',
    223: 'In-swinger',
    224: 'Out-swinger',
    225: 'Straight',
    236: 'Blocked Pass',
    238: 'Fair Play',
    240: 'GK Start',
    241: 'Indirect',
    266: 'Put Through',
    279: 'Kick Off',
    278: 'Tap',
    287: 'Over-arm',
    318: 'pass_xg',
    321: 'shot_xg'
}
